### ISSUE TITLE
List All Products in the Catalog

### ISSUE THREAD

**Issue by ImJ-Sys** [ImJ-Sys/Final-Project#7]
### Issue Description

**As a** user
**I need** the ability to list all products in the catalog
**So that** I can browse the entire inventory

### Acceptance Criteria
1. Display a list of all products
2. Paginate the list for large inventories
3. Include basic product details in the list

### Tasks
- [ ] Implement list view for all products
- [ ] Add pagination support
- [ ] Display product details (name, price, etc.)

### Additional Notes
Ensure the list is searchable and filterable.
